name: Deploy Code to Lambda
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy code to Lambda & Custom Dependencies Layer
        uses: denzalman/lambda-python-action@1.0.0
        with:
          lambda_layer_arn: "arn:aws:lambda:us-east-1:922311303087:layer:dpd-percent-for-art-notification-dependencies"
          lambda_name: "dpd-percent-for-art-notification"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
      - name: Update Environment Variables & Dependency Layer References
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          aws lambda update-function-configuration \
            --function-name dpd-percent-for-art-notification \
            --environment "Variables={DPDAppsProd_Email=${{ secrets.DPDAppsProd_Email }},DPDAppsProd_Password=${{ secrets.DPDAppsProd_Password }}, Dan_Email=${{ secrets.Dan_Email }},Kacie_Email=${{ secrets.Kacie_Email }},Sara_Email=${{ secrets.Sara_Email }},PercentForArt_ClientID=${{ secrets.PercentForArt_ClientID }},PercentForArt_ClientSecret=${{ secrets.PercentForArt_ClientSecret }} isAwsEnvironment=True}" \
            --layers \
              arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-pandas:24 \
              arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-numpy:13 \
              arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-shapely:1 \
              arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-requests:14 \
              arn:aws:lambda:us-east-1:922311303087:layer:dpd-percent-for-art-notification-dependencies:29

